 apiNames:
  - echo-api

  VersionSetNames:

 backendNames: [ignore]

 diagnosticNames: [ignore]

 loggerNames: [ignore]

 namedValueNames: [ignore]

 productNames: [ignore]

 subscriptionNames: [ignore]

 tagNames: [ignore]
  
 policyFragmentNames: [ignore]

 gatewayNames: [ignore]

 groupNames: [ignore]